#!/bin/bash
echo "$(date +"%Y-%m-%d %H:%M:%S")" "$@"
tenant_name="$1"
segment_name="$2"

if ! [[ "$tenant_name" ]] || ! [[ "$segment_name" ]]; then
	echo "Tenant and segment names required"
	exit 1
fi

if ! output=$(romana segment list "$tenant_name" -f json); then
	echo "Error listing segments for tenant '$tenant_name'"
	exit 1
fi
if [[ "$(jq -r --arg name "default" '.[0].Segments[] | select(.name==$name) // empty' <<< "$output")" ]]; then
	echo "Segment '$segment_name' already exists for tenant '$tenant_name'"
	exit 0
fi
if ! romana segment add "$tenant_name" "$segment_name"; then
	echo "Error running romana segment add"
	exit 1
fi
