apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: romana-agent
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: romana-agent
    spec:
      hostNetwork: true
      containers:
      - name: romana-agent
        image: quay.io/romana/agent:unspecified
        imagePullPolicy: Always
        args:
        - --cluster-ip-cidr=10.96.0.0/12
        - --cni-image=quay.io/romana/cni:unspecified
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-usr-local-bin
          mountPath: /host/usr/local/bin
        - name: host-etc-romana
          mountPath: /host/etc/romana
        - name: host-cni-bin
          mountPath: /host/opt/cni/bin
        - name: host-cni-net-d
          mountPath: /host/etc/cni/net.d
        - name: log-path
          mountPath: /var/log/romana
      volumes:
      - name: host-usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: host-etc-romana
        hostPath:
          path: /etc/romana
      - name: host-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: host-cni-net-d
        hostPath:
          path: /etc/cni/net.d
      - name: log-path
        hostPath:
          path: /var/log/romana
