#!/bin/bash
export GOPATH=/var/tmp/gopath
export PATH=/usr/local/go/bin:$PATH

go get -d github.com/romana/core/...

while IFS= read -r p; do
	pkgs+=("$p")
done < <(go list -f '{{ if eq .Name "main" }}{{ .ImportPath }}{{ end }}'  github.com/romana/core/... | grep -v /vendor/)

go install "${pkgs[@]}"

echo "export GOPATH=/var/tmp/gopath" >> ~/.profile
echo "export PATH=$PATH:/usr/local/go/bin " >> ~/.profile
