# TODO: use a more light-weight base image and packaging tool
FROM ubuntu:16.04
MAINTAINER Caleb Gilmour <cgilmour@romana.io>

COPY romana_aws /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/romana_aws"]
