#!/bin/bash

# Copyright (c) 2016 Pani Networks
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# Usage subcommand.
usage() {
	echo "romana: command-line tool for Romana administration"
	echo "Usage: romana <subcommmand> [options]"
	echo "       romana <subcommmand> help"
	echo "       romana [help]"
	echo "Subcommands:"
	echo "    add-host"
	echo "    remove-host"
	echo "    show-host"
	echo "    create-tenant"
	echo "    delete-tenant"
	echo "    show-tenant"
	echo "    add-segment"
	echo "    remove-segment"
}

# Variables used within the script
tenant_url=http://192.168.0.10:9602/
tenant_path="tenants"
topology_url=http://192.168.0.10:9603/
topology_path="hosts"

add_host() {
	if (( $# == 0 )) || [[ "$1" == "help" ]]; then
		echo "romana add-host <hostname> <host-ip> <romana-cidr> <agent-port>"
		return
	fi
	if (( $# != 4 )); then
		echo "ERROR: expected 4 parameters, received $#"
		return
	fi
	local hostname="$1" host_ip="$2" romana_cidr="$3" agent_port="$4"
	# TODO: add validation for the parameters
	post_data=$(printf '{"name": "%s", "ip": "%s", "romana_ip": "%s", "agent_port": %s}' "$hostname" "$host_ip" "$romana_cidr" "$agent_port")
	echo "Sending request to '${topology_url}${topology_path}': '$post_data'"
	curl -X POST -H "Content-Type: application/json" --data "$post_data" "${topology_url}${topology_path}"; printf "\n"
}

show_host() {
	# Without arguments, show all the hosts
	if (( $# == 0 )); then
		show_hosts
		return
	fi
	# Show usage.
	# TODO: What if the host's name is 'help' ?
	if [[ "$1" == "help" ]]; then
		echo "romana show-host [hostname...]"
		return
	fi

	# Get the list of hosts, save the data
	if ! response=$(curl -s -f -H "Content-Type: application/json" "${topology_url}${topology_path}"); then
		echo "Unable to fetch hosts using URL '${topology_url}${topology_path}'"
		return
	fi

	# For each hostname...
	for i in "$@"; do
		# Check that the host is in the list
		len=$(jq -r --arg host "$i" '.[] | select(.name==$host) | length' <<< "$response")
		if (( len == 0 )); then
			echo "Unable to find host '$i'"
			continue
		fi
		read -r hostname host_ip romana_cidr agent_port _ < <(jq -r --arg host "$i" '.[] | select(.name==$host) | "\(.name) \(.ip) \(.romana_ip) \(.agent_port)"' <<< "$response")
		printf "%-20s %15s %18s %5d\n" "$hostname" "$host_ip" "$romana_cidr" "$agent_port"
	done
}

show_hosts() {
	# Get the list of hosts
	if ! response=$(curl -s -f -H "Content-Type: application/json" "${topology_url}${topology_path}"); then
		echo "Unable to fetch hosts using URL '${topology_url}${topology_path}'"
		return
	fi

	# Determine the number of hosts
	num_hosts=$(jq 'length' <<< "$response")
	if (( num_hosts == 0 )); then
		echo "No hosts found."
		return
	fi
	# List the hosts
	printf "Listing %d host(s)\n" "$num_hosts"
	while read -r host _; do
		printf "%s\n" "$host"
	done < <(jq -r '.[].name' <<< "$response")
}

create_tenant() {
	if (( $# == 0 )) || [[ "$1" == "help" ]]; then
		echo "romana create-tenant <name>"
		return
	fi
	if (( $# != 1 )); then
		echo "ERROR: expected 1 parameters, received $#"
		return
	fi
	local tenant_name="$1"
	# TODO: handle other types of tenants
	echo "Resolving name to id in openstack"
	if ! project=$(openstack project show -f value -c id "$tenant_name"); then
		echo "Unable to find name in openstack."
		return
	fi

	post_data=$(printf '{"id": 0, "name": "%s"}' "$project")
	echo "Sending request to '${tenant_url}${tenant_path}': '$post_data'"
	curl -X POST -H "Content-Type: application/json" --data "$post_data" "${tenant_url}${tenant_path}"; printf "\n"
}

show_tenant() {
	# Without arguments, show all the tenants
	if (( $# == 0 )); then
		show_tenants
		return
	fi

	# Show usage.
	# TODO: What if the tenant's name is 'help' ?
	if [[ "$1" == "help" ]]; then
		echo "romana show-tenant [tenant-name...]"
		return
	fi

	# Get a list of all the tenants, save the data
	if ! response=$(curl -s -f -H "Content-Type: application/json" "${tenant_url}${tenant_path}"); then
		echo "Unable to fetch tenants using URL '${tenant_url}${tenant_path}'"
		return
	fi

	# For each project name...
	for i in "$@"; do
		# Resolve the project id in openstack
		if ! project=$(openstack project show -f value -c id "$i" 2>/dev/null); then
			echo "Unable to find name '$i' in openstack"
			continue
		fi
		# Find the tenant with that id
		len=$(jq -r --arg name "$project" '.[] | select(.Name==$name) | length' <<< "$response")
		if (( len == 0 )); then
			echo "Unable to find tenant '$project' ($i)"
			continue
		fi

		read -r id tenant _ < <(jq -r --arg name "$project" '.[] | select(.Name==$name) | "\(.Id) \(.Name)"' <<< "$response")

		# Get the list of segments
		if ! segment_list=$(curl -s -f -H "Content-Type: application/json" "${tenant_url}${tenant_path}/${id}/segments"); then
			echo "Unable to list segments for tenant '$tenant'"
			continue
		fi

		# Write the data
		printf "Tenant:%-32s (%s)\n" "$tenant" "$i"
		printf "Segments: "
		sep=""
		while read -r segment_name _; do
			printf "%s%s" "$sep" "$segment_name"
			sep=", "
		done < <(jq -r '.[].Name' <<< "$segment_list")
		printf "\n"
	done
}

show_tenants() {
	# Get the list of tenants
	if ! response=$(curl -s -f -H "Content-Type: application/json" "${tenant_url}${tenant_path}"); then
		echo "Unable to fetch tenants using URL '${tenant_url}${tenant_path}'"
		return
	fi
	# Determine the number of tenants
	num_tenants=$(jq 'length' <<< "$response")
	if (( num_tenants == 0 )); then
		echo "No tenants found."
		return
	fi
	# List the tenants
	printf "Listing %d tenant(s)\n" "$num_tenants"
	while read -r tenant _; do
		if ! project_name=$(openstack project show -f value -c name "$tenant" 2>/dev/null); then
			printf "%-32s # Unable to find name in openstack\n" "$tenant"
			continue
		fi
		printf "%-32s (%s)\n" "$tenant" "$project_name"
	done < <(jq -r '.[].Name' <<< "$response")
}

add_segment() {
	if (( $# == 0 )) || [[ "$1" == "help" ]]; then
		echo "romana add-segment <tenant-name> <segment-name>"
		return
	fi
	if (( $# != 2 )); then
		echo "ERROR: expected 2 parameters, received $#"
		return
	fi
	local tenant_name="$1" segment_name="$2"
	# TODO: handle this without duplication
	echo "Resolving name to id in openstack"
	if ! project=$(openstack project show -f value -c id "$tenant_name"); then
		echo "Unable to find name '$tenant_name' in openstack."
		return
	fi
	if ! response=$(curl -s -f -H "Content-Type: application/json" "${tenant_url}${tenant_path}"); then
		echo "Unable to fetch tenants using URL '${tenant_url}${tenant_path}'"
		return
	fi
	read -r tenant_id _ < <(jq -r --arg name "$project" '.[] | select(.Name==$name) | "\(.Id)"' <<< "$response")

	if ! [[ "$tenant_id" ]]; then
		echo "Unable to find tenant id using tenant ref '$project'"
		return
	fi

	post_data=$(printf '{"id": 0, "name": "%s"}' "$segment_name")
	segment_path="$tenant_path/$tenant_id/segments"
	echo "Sending request to '${tenant_url}${segment_path}': '$post_data'"
	curl -X POST -H "Content-Type: application/json" --data "$post_data" "${tenant_url}${segment_path}"; printf "\n"
}

# Show usage if no subcommand was provided
if (( $# == 0 )); then
	usage
	exit 9
fi

# Undocumented options to set topology and tenant URLs
while [[ "$1" = -* ]]; do
	case "$1" in
		--tenant-url)
			tenant_url="$2"
			shift 2
			;;
		--tenant-url=*)
			tenant_url="${1:13}"
			shift
			;;
		--topology-url)
			topology_url="$2"
			shift 2
			;;
		--topology-url=*)
			topology_url="${1:15}"
			shift
			;;
		*)
			# Silently ignore unrecognized parameter
			shift
			;;
	esac
done


# Dispatch to subcommand
case "$1" in
	add-host)
		shift
		add_host "$@"
		;;
	remove-host)
		echo "$1: Not implemented yet"
		;;
	show-host)
		shift
		show_host "$@"
		;;
	show-hosts)
		show_hosts
		;;
	create-tenant)
		shift
		create_tenant "$@"
		;;
	delete-tenant)
		echo "$1: Not implemented yet"
		;;
	show-tenant)
		shift
		show_tenant "$@"
		;;
	show-tenants)
		show_tenants
		;;
	add-segment)
		shift
		add_segment "$@"
		;;
	remove-segment)
		echo "$1: Not implemented yet"
		;;
	help)
		usage
		;;
	*)
		echo "Unknown subcommand '$1'"
		usage
		exit 1
		;;
esac
