#!/bin/bash

# Copyright (c) 2016 Pani Networks
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

image="cni-image"
volumes=(
  -v /var/log:/var/log
)
env=(
  -e CNI_ARGS="$CNI_ARGS"
  -e CNI_COMMAND="$CNI_COMMAND"
  -e CNI_IFNAME="$CNI_IFNAME"
  -e CNI_NETNS="$CNI_NETNS"
  -e CNI_CONTAINERID="$CNI_CONTAINERID"
  -e CNI_PATH="$CNI_PATH"
)
exec docker run --interactive --privileged --rm --net=host --pid=host "${env[@]}" "${volumes[@]}" "$image" "$@"
