# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Common VM configuration
  config.vm.box = "{{ distro_info[distro].box }}"
  config.vm.box_url = "{{ distro_info[distro].box_url }}"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision "shell", inline: <<-EOF
{% for cmd in distro_info[distro].bootstrap %}
    {{ cmd }}
{% endfor %}
  EOF
  # ---

  # Controller-specific VM configuration
  config.vm.define "{{ stack_name }}-controller" do |controller|
    config.vm.hostname = "ip-{{ stack_nodes.Controller.mgmt_ip | replace('.', '-') }}"
    controller.vm.network "private_network", ip: "{{ stack_nodes.Controller.mgmt_ip }}"
    controller.vm.provider "virtualbox" do |vb|
      vb.name = "{{ stack_name }}-controller"
      vb.memory = "{{ ram_size.controller[stack_type] }}"
      vb.customize ["modifyvm", :id, "--natnet1", "172.16.0.0/12"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
  # ---

  # Compute-specific VM configuration
{% for node in stack_nodes.ComputeNodes[:compute_nodes] %}
  config.vm.define "{{ stack_name }}-compute{{ '%02d' | format(loop.index) }}" do |compute|
    config.vm.hostname = "ip-{{ stack_nodes[node].mgmt_ip | replace('.', '-') }}"
    compute.vm.network "private_network", ip: "{{ stack_nodes[node].mgmt_ip }}"
    compute.vm.provider "virtualbox" do |vb|
      vb.name = "{{ stack_name }}-compute{{ '%02d' | format(loop.index) }}"
      vb.memory = "{{ ram_size.compute[stack_type] }}"
      vb.customize ["modifyvm", :id, "--natnet1", "172.16.0.0/12"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
{% endfor %}
  # ---
end
