# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Common VM configuration
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision "shell", inline: <<-EOF
    apt-get install python-apt
    printf '%s\n' '{{ lookup("file", romana_ssh_key + ".pub") }}' >> /home/ubuntu/.ssh/authorized_keys
  EOF
  # ---

  # Controller-specific VM configuration
  config.vm.define "{{ stack_name }}-controller" do |controller|
    config.vm.hostname = "ip-{{ stack_nodes.Controller.mgmt_ip | replace('.', '-') }}"
    controller.vm.network "private_network", ip: "{{ stack_nodes.Controller.mgmt_ip }}"
    controller.vm.provider "virtualbox" do |vb|
      vb.name = "{{ stack_name }}-controller"
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--natnet1", "172.16.0.0/12"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
  # ---

  # Compute-specific VM configuration
{% for node in stack_nodes.ComputeNodes[:compute_nodes] %}
  config.vm.define "{{ stack_name }}-compute{{ '%02d' | format(loop.index) }}" do |compute|
    config.vm.hostname = "ip-{{ stack_nodes[node].mgmt_ip | replace('.', '-') }}"
    compute.vm.network "private_network", ip: "{{ stack_nodes[node].mgmt_ip }}"
    compute.vm.provider "virtualbox" do |vb|
      vb.name = "{{ stack_name }}-compute{{ '%02d' | format(loop.index) }}"
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natnet1", "172.16.0.0/12"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
{% endfor %}
  # ---
end
